version: "3.8"

services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: discord-bot:production
    container_name: discord-bot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - BOT_TOKEN=${BOT_TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - GUILD_ID=${GUILD_ID}
      - DATABASE_URL=${DATABASE_URL}
      - QURAN_CLIENT_ID=${QURAN_CLIENT_ID}
      - QURAN_CLIENT_SECRET=${QURAN_CLIENT_SECRET}
      - QURAN_ENDPOINT=${QURAN_ENDPOINT}
    env_file:
      - .env
    volumes:
      - discord-bot-data:/app/db
    # Uncomment if your bot serves HTTP endpoints
    # ports:
    #   - "3000:3000"

    # Resource limits
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.5"
        reservations:
          memory: 128M
          cpus: "0.1"

    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    # Health check
    healthcheck:
      test: ["CMD-SHELL", 'node -e ''console.log("Bot is running")'' || exit 1']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  discord-bot-data:
    driver: local
